# Generated by Django 6.0.1 on 2026-01-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_cost_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('credit', 'Qarzga')], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
