# Generated by Django 6.0.1 on 2026-01-19 06:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_products_data(apps, schema_editor):
    """Mavjud Product ma'lumotlarini ProductVariant'ga ko'chirish"""
    Product = apps.get_model('store', 'Product')
    ProductVariant = apps.get_model('store', 'ProductVariant')
    Attribute = apps.get_model('store', 'Attribute')
    AttributeValue = apps.get_model('store', 'AttributeValue')
    SaleItem = apps.get_model('store', 'SaleItem')
    
    # Mavjud Product'larni olish (eski struktura)
    # Eski Product'larda hali cost_price, price, stock_quantity, sku, color bor
    for old_product in Product.objects.all():
        # ProductVariant yaratish
        variant = ProductVariant.objects.create(
            product=old_product,
            sku=getattr(old_product, 'sku', f'OLD-{old_product.id}') or f'OLD-{old_product.id}',
            cost_price=getattr(old_product, 'cost_price', 0) or 0,
            price=getattr(old_product, 'price', 0) or 0,
            stock_quantity=getattr(old_product, 'stock_quantity', 0) or 0,
            image=getattr(old_product, 'image', None),
            is_active=getattr(old_product, 'is_active', True),
        )
        
        # Color bo'lsa, Attribute va AttributeValue yaratish
        color = getattr(old_product, 'color', '').strip() if hasattr(old_product, 'color') else ''
        if color:
            attr, _ = Attribute.objects.get_or_create(
                name='color',
                defaults={'display_name': 'Rang'}
            )
            attr_value, _ = AttributeValue.objects.get_or_create(
                attribute=attr,
                value=color
            )
            variant.attribute_values.add(attr_value)
        
        # SaleItem'larni yangilash
        for sale_item in SaleItem.objects.filter(product=old_product):
            sale_item.product_old = old_product
            sale_item.variant = variant
            sale_item.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_color_alter_sale_payment_method'),
    ]

    operations = [
        # Avval yangi modellarni yaratish
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Atribut nomi')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name="Ko'rinadigan nom")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atribut',
                'verbose_name_plural': 'Atributlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Qiymat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.attribute', verbose_name='Atribut')),
            ],
            options={
                'verbose_name': 'Atribut qiymati',
                'verbose_name_plural': 'Atribut qiymatlari',
                'ordering': ['attribute', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kirib kelish narxi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Sotish narxi')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ombordagi miqdor')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Variant rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('attribute_values', models.ManyToManyField(related_name='variants', to='store.attributevalue', verbose_name='Atribut qiymatlari')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot varianti',
                'verbose_name_plural': 'Mahsulot variantlari',
                'ordering': ['product', '-created_at'],
            },
        ),
        # SaleItem'ga yangi field'lar qo'shish
        migrations.AddField(
            model_name='saleitem',
            name='product_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_sale_items', to='store.product', verbose_name='Mahsulot (eski)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant', verbose_name='Mahsulot varianti'),
        ),
        # Ma'lumotlarni ko'chirish
        migrations.RunPython(migrate_products_data, reverse_migration),
        # Eski field'larni olib tashlash
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Asosiy rasm'),
        ),
    ]
