# Generated by Django 6.0.1 on 2026-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_migrate_to_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='usd_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Dollar kursi (so'm)"),
        ),
    ]
