# Generated by Django 6.0.1 on 2026-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_sale_usd_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username (@siz)'),
        ),
    ]
