# Generated by Django 6.0.1 on 2026-02-25 10:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_lenta_products_metr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='telegram_username',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kirib kelish narxi'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="1 USD (so'm)")),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='store.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('market', 'date'), name='unique_market_date_rate')],
            },
        ),
    ]
