# Generated by Django 6.0.1 on 2026-02-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_convert_prices_to_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
