# Generated by Django 6.0.1 on 2026-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_sku_optional_for_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Yakunlangan'), ('returned', 'Qaytarilgan')], default='completed', max_length=20, verbose_name='Holati'),
        ),
    ]
