# Generated by Django 6.0.1 on 2026-03-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_sale_amounts_in_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Karta (USD)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Naqd (USD)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('mixed', 'Aralash (Naqd + Karta)'), ('credit', 'Qarzga')], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami summa (USD)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami (USD)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birlik narxi (USD)'),
        ),
    ]
