# Generated by Django 6.0.1 on 2026-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_sale_payment_card_amount_sale_payment_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Menejer'), ('seller', 'Sotuvchi')], default='seller', max_length=20, verbose_name='Rol'),
        ),
    ]
