# Generated by Django 6.0.1 on 2026-03-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unlimited_stock',
            field=models.BooleanField(default=False, verbose_name='Cheklanmagan zaxira'),
        ),
    ]
