# Generated by Django 6.0.1 on 2026-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productvariant_unlimited_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma (%)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='original_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirmasiz jami (USD)'),
        ),
    ]
